import org.apache.commons.lang3.ArrayUtils;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class MkMath {
    public static int gcd(int... args) {
        switch (args.length) {
            case 0:
                throw new IllegalArgumentException("1つ以上の整数が必要です");
            case 1:
                return args[0];
            case 2:
                return gcdOfTwoNumbers(args[0], args[1]);
            default:
                List<Integer> list = Arrays.stream(args).boxed().collect(Collectors.toList()).subList(2, args.length);
                list.add(0, gcdOfTwoNumbers(args[0], args[1]));
                Integer[] array = list.toArray(new Integer[list.size()]);
                return gcd(ArrayUtils.toPrimitive(array));
        }
    }

    public static int gcdOfTwoNumbers(int n, int m) {
        return m == 0 ? n : gcdOfTwoNumbers(m, n % m);
    }
}
