/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class MkMathTest {
    @Test public void testGcd() {
        assertEquals("パラメータが1つの場合",
                MkMath.gcd(42), 42);

        assertEquals("42と72の最大公約数は6",
                MkMath.gcd(42, 72), 6);

        assertEquals("2171と2839と5177の最大公約数は167",
                MkMath.gcd(2171, 2839, 5177), 167);
    }

    @Test(expected = IllegalArgumentException.class)
    public void throwsIllegalArguments() {
        MkMath.gcd();
    }
}
